export { default as Login } from './Login'
export { default as Home } from './Home'
export { default as NotFound } from './NotFound/Index'
export { default as ClassPage } from './ClassPage'
export { default as Classes } from './TeachersPages/ClassesPage'
